In [6]:
import numpy as np
import pandas as pd


df = pd.read_csv('car_data_29-05-2025_06:01:36.csv')
df.tail()

,price,brand,model,year,mileage,bodywork,fuel,volume,power,ID,DMFW,emission,transmission,door,seats,color,registered,origin,country_origin
4095,23510,Opel,Mokka,2024,5,Džip/SUV,Benzin,1199 cm3,100,26065885,NaN,Euro 6,Manuelni 6 brzina,4/5 vrata,5 sedišta,Siva,Nije registrovan,Domaće tablice,NaN
4096,24990,Fiat,Grande Panda,2025,0,Džip/SUV,Električni pogon,43.8 kWh,83,26058755,NaN,Euro 6,Automatski / poluautomatski,4/5 vrata,5 sedišta,Crvena,Nije registrovan,Na ime kupca,NaN
4097,18290,Fiat,Grande Panda,2025,0,Džip/SUV,Hibridni pogon (Benzin),1199 cm3,74,26060377,NaN,Euro 6,Automatski / poluautomatski,4/5 vrata,5 sedišta,Crvena,Nije registrovan,Na ime kupca,NaN
4098,2800,Volkswagen,Golf 5,2005,200000,Hečbek,Benzin,1598 cm3,85,26349002,NaN,Euro 4,Manuelni 6 brzina,2/3 vrata,5 sedišta,Plava,04.2026.,Domaće tablice,NaN
4099,19990,Toyota,Corolla,2022,121000,Limuzina,Hibridni pogon (Benzin),1798 cm3,90,26380401,NaN,Euro 6,Automatski / poluautomatski,4/5 vrata,5 sedišta,Braon,Nije registrovan,Domaće tablice,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4100 entries, 0 to 4099
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   price           4100 non-null   object
 1   brand           4100 non-null   object
 2   model           4100 non-null   object
 3   year            4100 non-null   int64
 4   mileage         4100 non-null   int64
 5   bodywork        4100 non-null   object
 6   fuel            4100 non-null   object
 7   volume          4100 non-null   object
 8   power           4100 non-null   object
 9   ID              4100 non-null   object
 10  DMFW            825 non-null    object
 11  emission        4099 non-null   object
 12  transmission    4100 non-null   object
 13  door            4100 non-null   object
 14  seats           4100 non-null   object
 15  color           4100 non-null   object
 16  registered      4100 non-null   object
 17  origin          4100 non-null   object
 18  country_origin  1811 non-null   object
dtypes: int64(2), object(17)
memory usage: 608.7+ KB

In [8]:
df.describe()

              year       mileage
count  4100.000000  4.100000e+03
mean   2015.036829  1.665957e+05
std       5.667614  9.598192e+04
min    1967.000000  0.000000e+00
25%    2011.000000  1.320000e+05
50%    2015.000000  1.770000e+05
75%    2019.000000  2.101288e+05
max    2025.000000  3.125857e+06